"""empty message

Revision ID: 478efe14b674
Revises: f94ab8091c80
Create Date: 2021-08-21 23:32:34.838307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478efe14b674'
down_revision = 'f94ab8091c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
